# Generated by Django 4.1.7 on 2023-05-29 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0002_alter_profile_email"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="user",),
        migrations.AddField(
            model_name="profile",
            name="lastname",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Фамилия"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Имя пользователя"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                default="profile/user-default.png",
                upload_to="profiles/",
                verbose_name="Фото профиля",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="username",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Имя пользователя",
            ),
        ),
    ]
