# Generated by Django 4.1.7 on 2023-05-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_profile_user_alter_profile_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="lastname",),
        migrations.RemoveField(model_name="profile", name="name",),
        migrations.AddField(
            model_name="profile",
            name="fullname",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="ФИО"
            ),
        ),
    ]
