# Generated by Django 4.1.7 on 2023-07-04 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_contactmessage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contactmessage", old_name="sender_name", new_name="sender",
        ),
    ]
