# Generated by Django 4.1.7 on 2023-07-05 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_rename_sender_name_contactmessage_sender"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactmessage",
            options={
                "ordering": ("-created",),
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={
                "ordering": ("-created",),
                "verbose_name": "Профиль",
                "verbose_name_plural": "Профили",
            },
        ),
    ]
