# Generated by Django 4.1.7 on 2023-07-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_profile_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(default="имя", max_length=200, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(
                blank=True, default="", max_length=13, null=True, verbose_name="Телефон"
            ),
        ),
    ]
