# Generated by Django 4.1.7 on 2023-07-07 16:16

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_alter_profile_first_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                default="",
                max_length=13,
                null=True,
                region=None,
                verbose_name="Телефон",
            ),
        ),
    ]
