# Generated by Django 4.1.7 on 2023-07-08 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_alter_profile_first_name_alter_profile_last_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="profile_image",),
    ]
