# Generated by Django 4.1.7 on 2023-06-19 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_profile_lastname_remove_profile_name_and_more"),
        ("orders", "0003_alter_order_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.profile",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="updated",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата обновления"
            ),
        ),
    ]
