# Generated by Django 4.1.7 on 2023-07-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_alter_order_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="phone_number",
            field=models.CharField(default="", max_length=50, verbose_name="Телефон"),
        ),
    ]
