# Generated by Django 4.1.7 on 2023-07-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_order_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="phone_number",
            field=models.CharField(
                blank=True, default="", max_length=13, null=True, verbose_name="Телефон"
            ),
        ),
    ]
