# Generated by Django 4.1.7 on 2023-05-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_product_manufacturer_product_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender_name", models.CharField(max_length=200)),
                ("sender_email", models.EmailField(max_length=500)),
                ("sender_subject", models.CharField(max_length=250)),
                ("sender_message", models.TextField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ("-created",),},
        ),
    ]
