# Generated by Django 4.1.7 on 2023-07-03 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_contactmessage_is_read_contactmessage_name_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="ContactMessage",),
    ]
